apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfstest
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
  storageClassName: nfs-client