apiVersion: v1
kind: PersistentVolume
metadata:
  name: miniopv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: minio-local-storage
  local:
    path: /data/minio-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - n167.njuics.cn
          - n168.njuics.cn
          - n169.njuics.cn
          - n170.njuics.cn
  