apiVersion: minio.min.io/v1
kind: Tenant
metadata:
  creationTimestamp: null
  name: tenant1
  namespace: default
scheduler:
  name: ""
spec:
  certConfig: {}
  console:
    consoleSecret:
      name: tenant1-console-secret
    image: minio/console:v0.3.14
    metadata:
      creationTimestamp: null
      name: tenant1
    replicas: 2
    resources: {}
  credsSecret:
    name: tenant1-creds-secret
  image: minio/minio:RELEASE.2020-11-19T23-48-16Z
  imagePullSecret: {}
  mountPath: /export
  requestAutoCert: true
  serviceName: tenant1-internal-service
  zones:
  - resources: {}
    servers: 4
    volumeClaimTemplate:
      apiVersion: v1
      kind: persistentvolumeclaims
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: minio-local-storage
      status: {}
    volumesPerServer: 1
status:
  availableReplicas: 0
  currentState: ""

---
apiVersion: v1
data:
  accesskey: NjIzMjhiYzMtMzA5Mi00OTk1LWI4NDQtMmQ1NTQ1ZWJiZDdk
  secretkey: OGEwZTRmOGMtNzQ0MS00NjFiLWIwNjEtZmJjMWIzMjM5YTZi
kind: Secret
metadata:
  creationTimestamp: null
  name: tenant1-creds-secret
  namespace: default

---
apiVersion: v1
data:
  CONSOLE_ACCESS_KEY: Mjk0ZDRiMDQtNmNlYS00ZmUyLWJlYTYtNmU3YjU4MmFiNjA1
  CONSOLE_HMAC_JWT_SECRET: YmM4NDJhYjMtZWM3Yy00YWRkLWI2OWUtMDFiNzMzMjEyYzJi
  CONSOLE_PBKDF_PASSPHRASE: NDYzMWJlZmYtMmQ0MC00YTRjLTk0M2QtMGRhYmFmNjkxZmNm
  CONSOLE_PBKDF_SALT: MDM1YjI2YzctZWYzMS00MzAyLWJhZGYtZWZmYmYyZjZkNmM3
  CONSOLE_SECRET_KEY: NmFlMmRiNDQtNjVlMS00OGY2LTk0NTgtNzViMjAzNjI2MDMx
kind: Secret
metadata:
  creationTimestamp: null
  name: tenant1-console-secret
  namespace: default

