apiVersion: batch/v1
kind: Job
metadata:
  name:  firstglusterjob
  namespace: default
spec:
  backoffLimit: 1
  template:
    spec:
      nodeName: n168.njuics.cn
      restartPolicy: Never
      containers: 
        - name: singlenode
          image: registry.cn-hangzhou.aliyuncs.com/liziming/oncemlio
          workingDir: /kaggle/input/bengaliai-cv19/
          command:
            - "python" 
            - "4Nodes.py"
            - "0"
          volumeMounts:
            - name: nfscodes
              mountPath: /kaggle/input/bengaliai-cv19/
      volumes:
        - name: nfscodes
          persistentVolumeClaim:
            claimName: nfstest
---
apiVersion: batch/v1
kind: Job
metadata:
  name:  secondglusterjob
  namespace: default
spec:
  backoffLimit: 1
  template:
    spec:
      nodeName: n168.njuics.cn
      restartPolicy: Never
      containers: 
        - name: singlenode
          image: registry.cn-hangzhou.aliyuncs.com/liziming/oncemlio
          workingDir: /kaggle/input/bengaliai-cv19/
          command:
            - "python" 
            - "4Nodes.py"
            - "1"
          volumeMounts:
            - name: nfscodes
              mountPath: /kaggle/input/bengaliai-cv19/
      volumes:
        - name: nfscodes
          persistentVolumeClaim:
            claimName: nfstest
---
apiVersion: batch/v1
kind: Job
metadata:
  name:  thirdglusterjob
  namespace: default
spec:
  backoffLimit: 1
  template:
    spec:
      nodeName: n169.njuics.cn
      restartPolicy: Never
      containers: 
        - name: singlenode
          image: registry.cn-hangzhou.aliyuncs.com/liziming/oncemlio
          workingDir: /kaggle/input/bengaliai-cv19/
          command:
            - "python" 
            - "4Nodes.py"
            - "2"
          volumeMounts:
            - name: nfscodes
              mountPath: /kaggle/input/bengaliai-cv19/
      volumes:
        - name: nfscodes
          persistentVolumeClaim:
            claimName: nfstest
---
apiVersion: batch/v1
kind: Job
metadata:
  name:  forthglusterjob
  namespace: default
spec:
  backoffLimit: 1
  template:
    spec:
      nodeName: n169.njuics.cn
      restartPolicy: Never
      containers: 
        - name: singlenode
          image: registry.cn-hangzhou.aliyuncs.com/liziming/oncemlio
          workingDir: /kaggle/input/bengaliai-cv19/
          command:
            - "python" 
            - "4Nodes.py"
            - "3"
          volumeMounts:
            - name: nfscodes
              mountPath: /kaggle/input/bengaliai-cv19/
      volumes:
        - name: nfscodes
          persistentVolumeClaim:
            claimName: nfstest