apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-test
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "glusterfs-cluster"
    path: "k8s-volume"
    readOnly: false
