apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: glusterfs
provisioner: kubernetes.io/glusterfs
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
allowVolumeExpansion: true
parameters:
   resturl: "http://210.28.132.167:8080" 
   restuser: "admin" 
   restauthenabled: "true"
   restuserkey: "123456"
   volumetype: none
   volumenameprefix: "k8s-dev"
   clusterid: "2822a2ec58e15eaa983f3f078e6e69e7"